openapi: 3.1.0
info:
  version: 1.0.0
  title: <Phoneboock node.js>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <Phoneboock in app>
tags:
  -name: Contacts
  description: Operation whit contacs
servers:
  - url: http://localhost:5000
  - url: https://nodejs-hw-mongodb-rghb.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml

      $ref: ../swagger/paths/contacts/post.yaml 
  /students/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
